version: '3.8'

services:
  backend:
    build: ./server
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - expensetracker-network

  frontend:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - expensetracker-network

networks:
  expensetracker-network:
    driver: bridge