

version: '3.8'

services:
  backend:
    build: ./server
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydb
      SPRING_DATASOURCE_USERNAME: mydb
      SPRING_DATASOURCE_PASSWORD: arghya
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    depends_on:
      - db
      - redis
    networks:
      - expensetracker-network

  frontend:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - expensetracker-network

  db:
    image: postgres:16.2-alpine # Using a specific version of PostgreSQL
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: mydb
      POSTGRES_PASSWORD: arghya
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - expensetracker-network

  redis:
    image: redis:7.2.5-alpine # Using a specific version of Redis
    ports:
      - "6379:6379"
    networks:
      - expensetracker-network

networks:
  expensetracker-network:
    driver: bridge

volumes:
  db_data:

