spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: mydb
    password: arghya
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
  h2:
    console:
      enabled: false
  data:
    redis:
      host: localhost
      port: 6379
      time-to-live: 60000 # 60 seconds (in milliseconds)

expensetracker:
  app:
    jwtSecret: thisIsAVeryLongAndSecureSecretKeyForJWTAuthenticationThatShouldBeAtLeast256BitsLongAndRandomlyGeneratedInProductionEnvironments
    jwtExpirationMs: 86400000 # 24 hours

logging:
  level:
    root: INFO
    com.expensetracker: DEBUG
